
services:
  bot:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./config.json:/app/config.json  # Монтируем локальный config.json в контейнер
    restart: always

