name: Deploy Telegram Bot

on:
  push:
    branches:
      - main  # Запускать при пуше в main или другой ветке, которую вы используете
  pull_request:
    branches:
      - main  # Запускать при PR в main или другую ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/buildx
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker build -t telegram-bot .

      - name: Deploy to server (using SSH)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
            cd /path/to/your/project
            git pull origin main
            docker-compose down
            docker-compose up -d
          EOF
